stages:
  - build & deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build-template:
  stage: build
  image: docker:latest
  script:
    - echo "DOCKER_TAG=$DOCKER_TAG"
    - echo -n "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    #- docker build -f "$CI_PROJECT_DIR"/ci/Dockerfile --pull -t "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}" .
    #- docker build --pull --build-arg CLI_VERSION="$SOURCE_BRANCH" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
    - docker build --pull --build-arg CLI_VERSION="$SOURCE_BRANCH" -f "$CI_PROJECT_DIR"/Dockerfile  -t "$CI_REGISTRY_IMAGE:${DOCKER_TAG}" . 
    #- docker push "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}"
    #- docker tag "$IMAGE_NAME" "$DOCKER_REPO":latest
    #- echo "DOCKER_REPO=$DOCKER_REPO"
    #- docker tag "$CI_REGISTRY_IMAGE" "$DOCKER_REPO":latest
    #- docker push "$DOCKER_REPO":latest
    - docker push "$CI_REGISTRY_IMAGE":${DOCKER_TAG}
    - docker push "$CI_REGISTRY_IMAGE":latest

Build Testing Docker Image:
  extends: .build-template
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix/'
      when: manual
  variables:
    DOCKER_TAG: ${CI_COMMIT_REF_SLUG}

Build Staging Docker Image:
  extends: .build-template
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^bugfix/'
      when: manual
  variables:
    DOCKER_TAG: ${CI_COMMIT_SHORT_SHA}
